### PR TITLE
Minor refactoring to structure and added wiki add/delete/change notifications

### PR DESCRIPTION
**Pull request by newodahs**
I threw this together quickly to refactor the current version of trac-slack-plugin to be a bit easier to extend (though more refactoring could be done) and to allow slack notifications for wiki add/delete/changes (change notifications currently controlled by regex for inclusion; may extend later to allow an exclude and include regex and perhaps a CSV or list mode as well).

This is just a first, unpolished pass at this, but it has been working for me over the past week or so.

### CODE REVIEW

**Review by wagnerpinheiro — COMMENTED** [review]
nice work! i'll test the refactory in the next fews days.

**Comment by trajano** [comment]
Does it work well?  Can we have it merged soon?

**Comment by newodahs** [comment]
No worries, glad I can help; if I have some other ideas/refactoring I'll submit them forward.

**Comment by trajano** [comment]
I just updated with `pip install --update git+https://github.com/wagnerpinheiro/trac-slack-plugin.git` and added the following to my trac.ini
<pre>
[slack]
wiki-webhook = (same as webhook)
wiki-channel = #general
wiki-username = Trac-Bot
wikichange = 1
</pre>
But I do not get any notifications for wiki changes

**Comment by newodahs** [comment]
Hmm...looks like a similar setup to what I have (minus the channel).  I do have mine setup on a Trac 1.0.1 instance.  Can you verify that it installed correctly (is Trac seeing the plugin?  Check your admin page, make sure it's still enabled, etc...).

Are you using the ticket-side of this configuration?  If so, is that still working?

My current setup also has all the parameters set in the configuration, mostly from testing (defaults should work fine though):
```
wiki-webhook = <edit>
wiki-channel = #trac
wiki-username = Trac-Bot
wikiadd = 1
wikidel = 1
wikichange = 1
wikipages = .*
```
I'll also take a look at my configuration more closely once I'm done working, make sure I didn't miss anything...

**Comment by newodahs** [comment]
No other configuration differences on my end; be sure that the component is completely enabled in the trac.ini (under the components section; and/or the admin->plugins page).  Also, I guess the `pip install` command should work (?) but generally I build Trac plugins directly and use easy_install to push it into place (this is also the recommended procedure for this plugin in the documentation).

Let me know if any of these things help or if you have more information on your environment and I'll poke some more... might not be a bad idea to move this to an issue too if you're still having trouble so it can be tracked a bit easier.

**Pull request merged**
